
class Name:
    MENU: str = "Menu"

    PLAYER_SHIP: str = "Your Ship"
    OTHER_SHIP: str = "Another's Ship"

    OPEN_SEA: str = "Open Sea"
    ROAR: str = "Devil's Roar"

    ISLANDS: str = "Islands"
    FORTRESSES: str = "Fortresses"


    DOMAIN_EM: str = "Seas of Emissarys"
    DOMAIN_AF: str = "Sea of Athena"
    DOMAIN_RB: str = "Sea of Reapers"
    DOMAIN_MA: str = "Sea of Merchants"
    DOMAIN_OOS: str = "Sea of Souls"
    DOMAIN_GH: str = "Sea of Hoarders"
    DOMAIN_SV: str = "Sea of Servants"
    DOMAIN_GF: str = "Sea of Guardians"

    SHOP_ANCIENT_SPIRE: str = "Ancient Spire Outpost Shop"
    SHOP_DAGGER_TOOTH: str = "Dagger Tooth Outpost Shop"
    SHOP_GALLEONS_GRAVE: str = "Galleon's Grave Outpost Shop"
    SHOP_MORROWS_PEAK: str = "Morrow's Peak Outpost Shop"
    SHOP_PLUNDER_OUTPOST: str = "Plunder Outpost Shop"
    SHOP_SANCTUARY_OUTPOST: str = "Sanctuary Outpost Shop"





    # region: Islands
    ANCIENT_GOLD_FORTRESS = "Ancient Gold Fortress"
    ANCIENT_SPIRE_OUTPOST = "Ancient Spire Outpost"
    ASHEN_REACHES = "Ashen Reaches"
    BARNACLE_CAY = "Barnacle Cay"
    BLACK_SAND_ATOLL = "Black Sand Atoll"
    BLACK_WATER_ENCLAVE = "Black Water Enclave"
    BLIND_MANS_LAGOON = "Blind Man’s Lagoon"
    BOOTY_ISLE = "Booty Isle"
    BOULDER_CAY = "Boulder Cay"
    BRIANS_BAZAAR = "Brian’s Bazaar"
    BRIMSTONE_ROCK = "Brimstone Rock"
    CANNON_COVE = "Cannon Cove"
    CASTAWAY_ISLE = "Castaway Isle"
    CHICKEN_ISLE = "Chicken Isle"
    CINDER_ISLET = "Cinder Islet"
    CRESCENT_ISLE = "Crescent Isle"
    CROOK_S_HOLLOW = "Crook's Hollow"
    CURSEWATER_SHORES = "Cursewater Shores"
    CUTLASS_CAY = "Cutlass Cay"
    DAGGER_TOOTH_OUTPOST = "Dagger Tooth Outpost"
    DEVIL_S_RIDGE = "Devil's Ridge"
    DISCOVERY_RIDGE = "Discovery Ridge"
    FETCHERS_REST = "Fetcher’s Rest"
    FLAMES_END = "Flame’s End"
    FLINTLOCK_PENINSULA = "Flintlock Peninsula"
    FOOLS_LAGOON = "Fools Lagoon"
    FORT_OF_THE_DAMNED = "Fort of the Damned"
    GALLEON_S_GRAVE_OUTPOST = "Galleon's Grave Outpost"
    GLOWSTONE_CAY = "Glowstone Cay"
    HIDDEN_SPRING_KEEP = "Hidden Spring Keep"
    IMPERIAL_CROWN_FORTRESS = "Imperial Crown Fortress"
    ISLE_OF_LAST_WORDS = "Isle of Last Words"
    KEEL_HAUL_FORT = "Keel Haul Fort"
    KRAKEN_WATCHTOWER = "Kraken Watchtower"
    KRAKENS_FALL = "Kraken’s Fall"
    LAGOON_OF_WHISPERS = "Lagoon of Whispers"
    LIAR_S_BACKBONE = "Liar's Backbone"
    LONE_COVE = "Lone Cove"
    LONELY_ISLE = "Lonely Isle"
    LOOKOUT_POINT = "Lookout Point"
    LOST_GOLD_FORT = "Lost Gold Fort"
    MAGMAS_TIDE = "Magma’s Tide"
    MARAUDER_S_ARCH = "Marauder's Arch"
    MERCY_S_END_FORTRESS = "Mercy's End Fortress"
    MERMAID_S_HIDEAWAY = "Mermaid's Hideaway"
    MOLTEN_SANDS_FORTRESS = "Molten Sands Fortress"
    MORROWS_PEAK_OUTPOST = "Morrow’s Peak Outpost"
    MUTINEER_ROCK = "Mutineer Rock"
    OLD_BRINESTONE_FORTRESS = "Old Brinestone Fortress"
    OLD_FAITHFUL_ISLE = "Old Faithful Isle"
    OLD_SALTS_ATOLL = "Old Salts Atoll"
    PARADISE_SPRING = "Paradise Spring"
    PICAROON_PALMS = "Picaroon Palms"
    PLUNDER_OUTPOST = "Plunder Outpost"
    PLUNDER_VALLEY = "Plunder Valley"
    PLUNDERERS_PLIGHT = "Plunderer’s Plight"
    PORT_MERRICK = "Port Merrick"
    RAPIER_CAY = "Rapier Cay"
    ROARING_SANDS = "Roaring Sands"
    ROARING_TRADERS = "Roaring Traders"
    ROYAL_CREST_FORTRESS = "Royal Crest Fortress"
    RUBYS_FALL = "Ruby’s Fall"
    RUM_RUNNER_ISLE = "Rum Runner Isle"
    SAILOR_S_BOUNTY = "Sailor's Bounty"
    SAILOR_S_KNOT_STRONGHOLD = "Sailor's Knot Stronghold"
    SALTY_SANDS = "Salty Sands"
    SANCTUARY_OUTPOST = "Sanctuary Outpost"
    SANDY_SHALLOWS = "Sandy Shallows"
    SCORCHED_PASS = "Scorched Pass"
    SCURVY_ISLEY = "Scurvy Isley"
    SEA_DOG_S_REST = "Sea Dog's Rest"
    SHARK_BAIT_COVE = "Shark Bait Cove"
    SHARK_FIN_CAMP = "Shark Fin Camp"
    SHARK_TOOTH_KEY = "Shark Tooth Key"
    SHIPWRECK_BAY = "Shipwreck Bay"
    SHIVER_RETREAT = "Shiver Retreat"
    SHRINE_OF_ANCIENT_TEARS = "Shrine of Ancient Tears"
    SHRINE_OF_THE_CORAL_TOMB = "Shrine of the Coral Tomb"
    SHRINE_OF_FLOODED_EMBRACE = "Shrine of Flooded Embrace"
    SHRINE_OF_HUNGERING = "Shrine of Hungering"
    SHRINE_OF_OCEAN_S_FORTUNE = "Shrine of Ocean's Fortune"
    SHRINE_OF_TRIBUTE = "Shrine of Tribute"
    SKULL_KEEP = "Skull Keep"
    SMUGGLERS__BAY = "Smugglers' Bay"
    SNAKE_ISLAND = "Snake Island"
    STEPHENS_SPOILS = "Stephen’s Spoils"
    THE_CROOKED_MASTS = "The Crooked Masts"
    THE_CROW_S_NEST_FORTRESS = "The Crow's Nest Fortress"
    THE_DEVILS_THIRST = "The Devil’s Thirst"
    THE_FINEST_TRADING_POST = "The Finest Trading Post"
    THE_FORSAKEN_BRINK = "The Forsaken Brink"
    THE_NORTH_STAR_SEAPOST = "The North Star Seapost"
    THE_REAPER_S_HIDEOUT = "The Reaper's Hideout"
    THE_SUNKEN_GROVE = "The Sunken Grove"
    THE_SPOILS_OF_PLENTY_STORE = "The Spoils of Plenty Store"
    THE_WILD_TREASURES_STORE = "The Wild Treasures Store"
    THE_CORAL_FORTRESS = "The Coral Fortress"
    THIEVES__HAVEN = "Thieves' Haven"
    THREE_PACES_EAST_SEAPOST = "Three Paces East Seapost"
    TRAITOR_S_FATE_FORTRESS = "Traitor's Fate Fortress"
    TREASURY_OF_THE_SUNKEN_SHORES = "Treasury of the Sunken Shores"
    TREASURY_OF_THE_LOST_ANCIENTS = "Treasury of the Lost Ancients"
    TREASURY_OF_THE_SECRET_WILDS = "Treasury of the Secret Wilds"
    TRI_ROCK_ISLE = "Tri-Rock Isle"
    TWIN_GROVES = "Twin Groves"
    # endregion

    #region Treasury
    SUNKEN_SHORES = "Treasury of the Sunken Shores"
    LOST_ANCIENTS = "Treasury of the Lost Ancients"
    SECRET_WILDS = "Treasury of the Secret Wilds"
    #endregion



islands = []